version: "3.3"

services:
      backend:
       build: ./backend
       networks:
         - webnet
       ports:
         - 8000:8000

      frontend:
       
       build: ./frontend
       networks:
         - webnet
       ports:
         - 5000:5000
networks:
  webnet:
